# untuk melakukan pengetest an API 
GET https://team-a-spk-internet-service-provider.vercel.app/api/v1/

### REGISTER
POST https://team-a-spk-internet-service-provider.vercel.app/api/v1/auth/register
Content-Type: application/json

{
    "name": "member baru",
    "phoneNumber": "08111197811",
    "email": "memberbar2@mail.com",
    "password": "password",
    "address" : "Talun, Blitar",
}

### LOGIN
POST https://team-a-spk-internet-service-provider.vercel.app/api/v1/auth/login/
content-type: application/json

{
    "email": "member@example.com",
    "password": "password"
}

### FETCH MEMBERS
GET https://team-a-spk-internet-service-provider.vercel.app/api/v1/memberships/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNseGd5bGZiaDAwMDIxM3N6cHcxM3doNTAiLCJuYW1lIjoiSmFuZSBTbWl0aCIsImVtYWlsIjoidmllcnkxNTEwMjAwMkBnbWFpbC5jb20iLCJwaG9uZU51bWJlciI6Iis5ODc2NTQzMjEwIiwiaWF0IjoxNzE4NTI2Mjg4LCJleHAiOjE3MTg2MTI2ODh9.kf7_daKcCLg-oH-aSsdL-ZgIvhpxfBc1uL5EivwGxbo

###
GET https://team-a-spk-internet-service-provider.vercel.app/api/v1/memberships/clxco1g7f0004rbc2egd9ti6k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNseGNvMWc3ZjAwMDRyYmMyZWdkOXRpNmsiLCJuYW1lIjoiSmFuZSBTbWl0aCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJwaG9uZU51bWJlciI6Iis5ODc2NTQzMjEwIiwiaWF0IjoxNzE4NDU4MTQ0LCJleHAiOjE3MTg1NDQ1NDR9.hPAkSvCuXlBTbMbqbPrYA6N7Z8KFAX0-EYhjJbMumgY

###
POST https://team-a-spk-internet-service-provider.vercel.app/api/v1/memberships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNseGd5bGYzazAwMDAxM3N6ZWF6eTJncGoiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6Im1lbWJlckBleGFtcGxlLmNvbSIsInBob25lTnVtYmVyIjoiKzEyMzQ1Njc4OTAiLCJyb2xlIjoiTUVNQkVSIiwiYWRkcmVzcyI6IkJsaXRhciIsImlhdCI6MTcxOTA1MzA1MCwiZXhwIjoxNzE5MTM5NDUwfQ.JaMVvhM5pBxHjfGVJLUQcd-sDTAEW7bisf0x9BCoZro
Content-Type: application/json

{
    "locationDistance": 0.8,
    "problem": "DAMAGE",
    "status": "PENDING",
    "description": "masalah hidup",
    "timeOfIncident": "2024-06-07T03:45:41.134Z",
    "cost": 200
}